# Generated by Django 6.0.3 on 2026-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_edit_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_edit_fleet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_edit_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_edit_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='can_edit_team',
            field=models.BooleanField(default=False),
        ),
    ]
