# Generated by Django 6.0.3 on 2026-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_lead_assigned_to_lead_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Actively Looking'), ('NEGOTIATING', 'In Negotiation'), ('PURCHASED', 'Purchased'), ('NOT_INTERESTED', 'Not Interested'), ('LOST', 'Lost')], default='NEW', max_length=20),
        ),
    ]
