# Generated by Django 6.0.4 on 2026-04-25 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter')], default='', help_text='If empty, falls back to LLM_PROVIDER env var.', max_length=16)),
                ('openai_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('openai_model', models.CharField(blank=True, default='', max_length=64)),
                ('gemini_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('gemini_model', models.CharField(blank=True, default='', max_length=64)),
                ('deepseek_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('deepseek_model', models.CharField(blank=True, default='', max_length=64)),
                ('openrouter_api_key', models.CharField(blank=True, default='', max_length=256)),
                ('openrouter_model', models.CharField(blank=True, default='', max_length=64)),
                ('daily_llm_calls_per_user', models.PositiveIntegerField(default=0, help_text='Max LLM calls per user per UTC day. 0 = unlimited. Applies to user-initiated calls (chat Q&A, manual triage, connection test). Staff users bypass the limit.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent settings',
                'verbose_name_plural': 'Agent settings',
            },
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('enrichment', 'Lead enrichment'), ('qa', 'Portal lead chat'), ('website_chat', 'Website visitor chat'), ('email_triage', 'Email triage'), ('blog_draft', 'Blog draft helper'), ('test', 'Connection test')], default='qa', max_length=16)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_kind', models.CharField(blank=True, default='', max_length=64)),
                ('lead_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user whose action triggered this call, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='agent_llmca_created_8863ed_idx'), models.Index(fields=['provider', '-created_at'], name='agent_llmca_provide_7d5276_idx'), models.Index(fields=['user', '-created_at'], name='agent_llmca_user_id_abaf03_idx')],
            },
        ),
    ]
