# Generated by Django 6.0.3 on 2026-05-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_view', '0002_service'),
        ('client_view', '0002_teammember'),
    ]

    operations = [
    ]
