# Generated by Django 6.0.3 on 2026-04-17 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('category', models.CharField(choices=[('limo', 'Limousine'), ('shuttle', 'Shuttle Bus'), ('motorcoach', 'Motorcoach'), ('sprinter', 'Sprinter'), ('recreation', 'Recreation Vehicle'), ('custom', 'Custom Vehicle')], default='custom', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('features', models.TextField(blank=True, help_text='One feature per line - rendered as a bulleted list.')),
                ('passenger_capacity', models.CharField(blank=True, max_length=40)),
                ('hero_image', models.ImageField(upload_to='vehicles/')),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('alt_text', models.CharField(blank=True, help_text='Image Description', max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='garage.vehicle')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
