# Generated by Django 6.0.3 on 2026-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='video',
            field=models.FileField(blank=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Image or video description', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehicles/'),
        ),
    ]
