# Generated by Django 6.0.3 on 2026-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_add_video_to_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='used_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
