# Generated by Django 6.0.3 on 2026-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Story', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('body', models.TextField(default="For over 40 years Executive Coach Builders has been your premier luxury limousine and bus builder. Established in 1976 by John Bumgarner, by 1986 ECB was producing more than 400 limousines a year in an onsite facility in Springfield MO. Roger Farris took over ownership in 1981 and expanded the operation throughout the early '80s. In an article published by LCT magazine in 1986, Farris explained that he approached the Limousine business first as a consumer. Having purchased ECB from Bumgarner, he was drawn into conversation about buying the company after purchasing a limousine himself. He explained that he was drawn to ECB because of their distinct quality. Originally specializing in just two limousines, Executive Coach has since expanded its product offering to more than 25 different vehicles and custom modifications.\n\nDavid Bakare, the current owner, took over operation of ECB in 1993 and has since expanded Executive Coach to be the Premier Luxury Limousine and Bus Builder for the United States and abroad!\n\nECB currently produces around 600 limousines per year. With headquarters located in Springfield, Missouri ECB provides luxury stretch limousines and buses worldwide. Known as a manufacturer of luxury limousines from, Ford, Cadillac, Mercedes, Rolls Royce, Bentley, BMW, and Hummer chassis, ECB takes great pride in delivering quality products.\n\nWith a dedicated and highly experienced staff of employees, ECB has built a reputation as a customer service oriented company. The plant managers and supervisors alone posess 200 years of experience between them, working together and applying the knowledge to craft some of the finest vehicles in the business.\n\nExecutive Coach Builders is still committed to high quality vehicle modification and production. Our vehicles are QVM certified, made in the U.S., modified to fit your needs, and developed with the customer in mind. With over 40 years of industry experience, Executive Coach Builders is redefining what luxury transportation should be.\n\nWhen it comes to designing and producing limousines, integrity and exceptional industry knowledge make Executive Coach Builders the only choice. Schedule a visit today to check out our production facility, or talk to a representative by calling 417-831-3535!")),
            ],
            options={
                'verbose_name': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='_', max_length=100)),
                ('file_value', models.FileField(default='_', upload_to='site_settings/')),
                ('text_value', models.CharField(blank=True, default='_', max_length=255)),
                ('file', models.BooleanField(default='0')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
