# Generated by Django 6.0.3 on 2026-04-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='primaryCenterVideo',
            new_name='primary_center_video',
        ),
    ]
