# Generated by Django 6.0.3 on 2026-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0002_rename_primarycentervideo_sitesettings_primary_center_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='primary_center_video',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name',
            field=models.CharField(default='_', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='type',
            field=models.CharField(choices=[('T', 'TEXT'), ('V', 'VIDEO'), ('I', 'IMAGE')], default='T', max_length=25),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='value',
            field=models.CharField(default='_', max_length=255),
        ),
    ]
