# Generated by Django 6.0.3 on 2026-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0003_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='type',
            field=models.CharField(choices=[('T', 'TEXT'), ('V', 'VIDEO'), ('I', 'IMAGE')], default='T', max_length=5),
        ),
    ]
