# Generated by Django 6.0.3 on 2026-04-22 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0004_alter_sitesettings_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='SiteSetting',
        ),
    ]
