# Generated by Django 6.0.3 on 2026-04-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0005_rename_sitesettings_sitesetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='value',
            new_name='text_value',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='type',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='file',
            field=models.BooleanField(default='0'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='file_value',
            field=models.FileField(default='_', upload_to='site_settings/'),
        ),
    ]
