# Generated by Django 6.0.3 on 2026-04-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0006_rename_value_sitesetting_text_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='file_value',
            field=models.FileField(blank=True, default='_', upload_to='site_settings/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='name',
            field=models.CharField(blank=True, default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='text_value',
            field=models.CharField(blank=True, default='_', max_length=255),
        ),
    ]
