# Generated by Django 6.0.3 on 2026-04-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edit_site', '0007_alter_sitesetting_file_value_alter_sitesetting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='file_value',
            field=models.FileField(default='_', upload_to='site_settings/'),
        ),
    ]
