# Generated by Django 6.0.3 on 2026-05-08 13:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('video', models.FileField(blank=True, upload_to='blog/videos/')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250, unique_for_date='publish')),
                ('summary', models.CharField(blank=True, default='', help_text='Short excerpt for the public news list and search previews.', max_length=500)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newshroom_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='blog_articl_publish_2a54df_idx')],
            },
        ),
    ]
