# Generated by Django 6.0.3 on 2026-05-08 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=120)),
                ('signature', models.TextField(blank=True, default='', help_text='Auto-appended to outbound mail (two blank lines above signature).')),
                ('imap_enabled', models.BooleanField(default=False)),
                ('imap_host', models.CharField(blank=True, default='', max_length=255)),
                ('imap_port', models.PositiveIntegerField(blank=True, null=True)),
                ('imap_username', models.CharField(blank=True, default='', max_length=255)),
                ('imap_password', models.CharField(blank=True, default='', max_length=255)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('imap_folder', models.CharField(blank=True, default='', max_length=120)),
                ('internal_domains', models.CharField(blank=True, default='', help_text='Comma-separated domains we treat as internal (e.g. ecblimo.com).', max_length=500)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_poll_status', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email settings',
                'verbose_name_plural': 'Email settings',
            },
        ),
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=998, unique=True)),
                ('in_reply_to', models.CharField(blank=True, db_index=True, default='', max_length=998)),
                ('references', models.TextField(blank=True, default='')),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('raw_headers', models.JSONField(blank=True, default=dict)),
                ('attachment_names', models.JSONField(blank=True, default=list)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (unmatched)'), ('linked', 'Linked to lead'), ('internal_reply', 'Internal reply'), ('filtered', 'Filtered (headers/heuristics)')], default='pending', max_length=24)),
                ('filter_reason', models.CharField(blank=True, default='', max_length=120)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_emails', to='leads.lead')),
                ('linked_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.leadmessage')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', '-received_at'], name='emailing_in_status_a6891c_idx'), models.Index(fields=['from_email'], name='emailing_in_from_em_a06ae1_idx')],
            },
        ),
    ]
